using DevExpress.XtraCharts;
using System;
using System.Windows.Forms;

namespace HiddenLabelsSample {
    public partial class Form1 : Form {
        public Form1() {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            gspTableAdapter1.Fill(gspDataSet1.GSP);
        }

        #region #LabelsHidding
        private void OnCustomDrawSeriesPoint(object sender, CustomDrawSeriesPointEventArgs e) {
            if (e.SeriesPoint.Values[0] < 1) {
                e.LabelText = String.Empty;
            }
        }
        #endregion #LabelsHidding
    }
}
